# Generated by Django 2.2.6 on 2019-11-14 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=30, verbose_name='Endereço')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('telefone', models.CharField(max_length=14, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name_plural': 'Morador',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('telefone', models.CharField(max_length=14, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name_plural': 'Visitante',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('cor', models.CharField(max_length=10, verbose_name='Cor')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Morador', verbose_name='Morador')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name_plural': 'Veiculo',
            },
        ),
        migrations.CreateModel(
            name='AcessoInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=7)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Morador')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Veiculo')),
            ],
            options={
                'verbose_name_plural': 'Acesso Interno',
            },
        ),
        migrations.CreateModel(
            name='AcessoExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.CharField(max_length=10)),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('livre', models.CharField(default='nao', max_length=20)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Veiculo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Visitante')),
            ],
            options={
                'unique_together': {('visitante', 'livre'), ('cartao', 'livre')},
            },
        ),
    ]
