# Generated by Django 2.2.6 on 2019-11-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20191114_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
    ]
