# Generated by Django 2.2.6 on 2019-11-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20191121_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessoexterno',
            options={'verbose_name_plural': 'Acesso Externo'},
        ),
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF*'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='endereco',
            field=models.CharField(max_length=30, verbose_name='Endereço*'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=10, verbose_name='Cor*'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=20, verbose_name='Modelo*'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='morador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Morador', verbose_name='Morador*'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa*'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Visitante', verbose_name='Visitante*'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF*'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome*'),
        ),
    ]
